import type { Employee, PaginatedResponse, EmployeeFilters } from '@/types';

const MOCK_EMPLOYEES: Employee[] = [
  {
    id: 'emp-001',
    firstName: 'Ash',
    lastName: 'Rojas',
    fullName: 'Rojas, Ash',
    username: 'ash',
    email: 'ash.rojas@eztruckrepair.com',
    role: 'Admin',
    department: 'Office',
    shift: 'Main Shift 1',
    status: 'active',
    isPunchedIn: false,
    weeklyHours: 38.5,
    overtimeHours: 0,
    hireDate: '2021-01-15',
    phone: '(555) 100-0001',
  },
  {
    id: 'emp-002',
    firstName: 'Justin',
    lastName: 'Naranjo',
    fullName: 'Naranjo, Justin',
    username: 'justin',
    email: 'justin.naranjo@eztruckrepair.com',
    role: 'Employee',
    department: 'Mechanical Floor',
    shift: 'Main Shift 1',
    status: 'punched-in',
    isPunchedIn: true,
    weeklyHours: 37.25,
    overtimeHours: 0,
    hireDate: '2021-03-20',
    phone: '(555) 100-0002',
  },
  {
    id: 'emp-003',
    firstName: 'Jesus',
    lastName: 'Garcia',
    fullName: 'Garcia, Jesus',
    username: 'garcia.j',
    email: 'jesus.garcia@eztruckrepair.com',
    role: 'Employee',
    department: 'Mechanical Floor',
    shift: 'Main Shift 1',
    status: 'punched-in',
    isPunchedIn: true,
    weeklyHours: 38.5,
    overtimeHours: 0,
    hireDate: '2021-05-10',
    phone: '(555) 100-0003',
  },
  {
    id: 'emp-004',
    firstName: 'Bernardo',
    lastName: 'Grossi',
    fullName: 'Grossi, Bernardo',
    username: 'grossi.b',
    email: 'bernardo.grossi@eztruckrepair.com',
    role: 'Employee',
    department: 'Mechanical Floor',
    shift: 'Main Shift 1',
    status: 'punched-in',
    isPunchedIn: true,
    weeklyHours: 40.0,
    overtimeHours: 0,
    hireDate: '2021-08-22',
    phone: '(555) 100-0004',
  },
  {
    id: 'emp-005',
    firstName: 'Miguel',
    lastName: 'Lopez',
    fullName: 'Lopez, Miguel',
    username: 'lopez.m',
    email: 'miguel.lopez@eztruckrepair.com',
    role: 'Employee',
    department: 'Mechanical Floor',
    shift: 'Main Shift 1',
    status: 'punched-in',
    isPunchedIn: true,
    weeklyHours: 39.75,
    overtimeHours: 0,
    hireDate: '2022-02-14',
    phone: '(555) 100-0005',
  },
  {
    id: 'emp-006',
    firstName: 'Jose',
    lastName: 'Retana',
    fullName: 'Retana, Jose',
    username: 'retana.j',
    email: 'jose.retana@eztruckrepair.com',
    role: 'Employee',
    department: 'Mechanical Floor',
    shift: 'Main Shift 1',
    status: 'punched-in',
    isPunchedIn: true,
    weeklyHours: 36.0,
    overtimeHours: 0,
    hireDate: '2022-04-01',
    phone: '(555) 100-0006',
  },
  {
    id: 'emp-007',
    firstName: 'Zafar',
    lastName: 'Khatamov',
    fullName: 'Khatamov, Zafar',
    username: 'khatamov.z',
    email: 'zafar.khatamov@eztruckrepair.com',
    role: 'Employee',
    department: 'Office',
    shift: 'Main Shift 1',
    status: 'punched-in',
    isPunchedIn: true,
    weeklyHours: 32.5,
    overtimeHours: 0,
    hireDate: '2022-06-15',
    phone: '(555) 100-0007',
  },
  {
    id: 'emp-008',
    firstName: 'islomjon',
    lastName: 'abdurahmanov',
    fullName: 'abdurahmanov, islomjon',
    username: 'abdurahmanov.i',
    email: 'islomjon.abdurahmanov@eztruckrepair.com',
    role: 'Employee',
    department: 'Mechanical Floor',
    shift: 'Main Shift 4',
    status: 'active',
    isPunchedIn: false,
    weeklyHours: 40.0,
    overtimeHours: 2.5,
    hireDate: '2022-09-01',
    phone: '(555) 100-0008',
  },
  {
    id: 'emp-009',
    firstName: 'Oybek',
    lastName: 'TURDIMURODOV',
    fullName: 'TURDIMURODOV, Oybek',
    username: 'turdimurodov.o',
    email: 'oybek.turdimurodov@eztruckrepair.com',
    role: 'Employee',
    department: 'Mechanical Floor',
    shift: 'Main Shift 1',
    status: 'punched-in',
    isPunchedIn: true,
    weeklyHours: 41.0,
    overtimeHours: 1.0,
    hireDate: '2022-11-07',
    phone: '(555) 100-0009',
  },
  {
    id: 'emp-010',
    firstName: 'Josue',
    lastName: 'Delgado',
    fullName: 'Delgado, Josue',
    username: 'delgado.j',
    email: 'josue.delgado@eztruckrepair.com',
    role: 'Employee',
    department: 'Mechanical Floor',
    shift: 'Main Shift 1',
    status: 'punched-in',
    isPunchedIn: true,
    weeklyHours: 42.5,
    overtimeHours: 2.5,
    hireDate: '2023-01-09',
    phone: '(555) 100-0010',
  },
  {
    id: 'emp-011',
    firstName: 'Carlos',
    lastName: 'Martinez',
    fullName: 'Martinez, Carlos',
    username: 'martinez.c',
    email: 'carlos.martinez@eztruckrepair.com',
    role: 'Employee',
    department: 'Mechanical Floor',
    shift: 'Main Shift 1',
    status: 'active',
    isPunchedIn: false,
    weeklyHours: 35.0,
    overtimeHours: 0,
    hireDate: '2023-03-15',
    phone: '(555) 100-0011',
  },
  {
    id: 'emp-012',
    firstName: 'Marco',
    lastName: 'Hernandez',
    fullName: 'Hernandez, Marco',
    username: 'hernandez.m',
    email: 'marco.hernandez@eztruckrepair.com',
    role: 'Employee',
    department: 'Parts',
    shift: 'Main Shift 1',
    status: 'punched-in',
    isPunchedIn: true,
    weeklyHours: 36.25,
    overtimeHours: 0,
    hireDate: '2023-05-20',
    phone: '(555) 100-0012',
  },
  {
    id: 'emp-013',
    firstName: 'David',
    lastName: 'Torres',
    fullName: 'Torres, David',
    username: 'torres.d',
    email: 'david.torres@eztruckrepair.com',
    role: 'Employee',
    department: 'Mechanical Floor',
    shift: 'Main Shift 1',
    status: 'punched-in',
    isPunchedIn: true,
    weeklyHours: 37.5,
    overtimeHours: 0,
    hireDate: '2023-07-11',
    phone: '(555) 100-0013',
  },
  {
    id: 'emp-014',
    firstName: 'Luis',
    lastName: 'Gomez',
    fullName: 'Gomez, Luis',
    username: 'gomez.l',
    email: 'luis.gomez@eztruckrepair.com',
    role: 'Employee',
    department: 'Mechanical Floor',
    shift: 'Main Shift 1',
    status: 'active',
    isPunchedIn: false,
    weeklyHours: 0,
    overtimeHours: 0,
    hireDate: '2023-09-04',
    phone: '(555) 100-0014',
  },
  {
    id: 'emp-015',
    firstName: 'Ramon',
    lastName: 'Flores',
    fullName: 'Flores, Ramon',
    username: 'flores.r',
    email: 'ramon.flores@eztruckrepair.com',
    role: 'Employee',
    department: 'Mechanical Floor',
    shift: 'Main Shift 2',
    status: 'punched-in',
    isPunchedIn: true,
    weeklyHours: 38.0,
    overtimeHours: 0,
    hireDate: '2023-10-17',
    phone: '(555) 100-0015',
  },
  {
    id: 'emp-016',
    firstName: 'Pedro',
    lastName: 'Jimenez',
    fullName: 'Jimenez, Pedro',
    username: 'jimenez.p',
    email: 'pedro.jimenez@eztruckrepair.com',
    role: 'Employee',
    department: 'Office',
    shift: 'Main Shift 1',
    status: 'punched-in',
    isPunchedIn: true,
    weeklyHours: 40.0,
    overtimeHours: 0,
    hireDate: '2024-01-08',
    phone: '(555) 100-0016',
  },
  {
    id: 'emp-017',
    firstName: 'Juan',
    lastName: 'Rodriguez',
    fullName: 'Rodriguez, Juan',
    username: 'rodriguez.j',
    email: 'juan.rodriguez@eztruckrepair.com',
    role: 'Employee',
    department: 'Mechanical Floor',
    shift: 'Main Shift 1',
    status: 'punched-in',
    isPunchedIn: true,
    weeklyHours: 38.75,
    overtimeHours: 0,
    hireDate: '2024-02-19',
    phone: '(555) 100-0017',
  },
  {
    id: 'emp-018',
    firstName: 'Eduardo',
    lastName: 'Morales',
    fullName: 'Morales, Eduardo',
    username: 'morales.e',
    email: 'eduardo.morales@eztruckrepair.com',
    role: 'Employee',
    department: 'Mechanical Floor',
    shift: 'Main Shift 1',
    status: 'punched-in',
    isPunchedIn: true,
    weeklyHours: 36.5,
    overtimeHours: 0,
    hireDate: '2024-04-01',
    phone: '(555) 100-0018',
  },
  {
    id: 'emp-019',
    firstName: 'Sergio',
    lastName: 'Cruz',
    fullName: 'Cruz, Sergio',
    username: 'cruz.s',
    email: 'sergio.cruz@eztruckrepair.com',
    role: 'Employee',
    department: 'Parts',
    shift: 'Main Shift 1',
    status: 'active',
    isPunchedIn: false,
    weeklyHours: 24.0,
    overtimeHours: 0,
    hireDate: '2024-06-14',
    phone: '(555) 100-0019',
  },
  {
    id: 'emp-020',
    firstName: 'Fernando',
    lastName: 'Rivera',
    fullName: 'Rivera, Fernando',
    username: 'rivera.f',
    email: 'fernando.rivera@eztruckrepair.com',
    role: 'Employee',
    department: 'Mechanical Floor',
    shift: 'Main Shift 1',
    status: 'punched-in',
    isPunchedIn: true,
    weeklyHours: 40.0,
    overtimeHours: 0,
    hireDate: '2024-08-26',
    phone: '(555) 100-0020',
  },
  {
    id: 'emp-021',
    firstName: 'Miguel',
    lastName: 'Vargas',
    fullName: 'Vargas, Miguel',
    username: 'vargas.m',
    email: 'miguel.vargas@eztruckrepair.com',
    role: 'Employee',
    department: 'Mechanical Floor',
    shift: 'Main Shift 1',
    status: 'punched-in',
    isPunchedIn: true,
    weeklyHours: 38.0,
    overtimeHours: 0,
    hireDate: '2024-10-07',
    phone: '(555) 100-0021',
  },
  {
    id: 'emp-022',
    firstName: 'Roberto',
    lastName: 'Medina',
    fullName: 'Medina, Roberto',
    username: 'medina.r',
    email: 'roberto.medina@eztruckrepair.com',
    role: 'Employee',
    department: 'Mechanical Floor',
    shift: 'Main Shift 1',
    status: 'active',
    isPunchedIn: false,
    weeklyHours: 16.0,
    overtimeHours: 0,
    hireDate: '2025-01-13',
    phone: '(555) 100-0022',
  },
  // Archived employees
  {
    id: 'emp-023',
    firstName: 'Daniel',
    lastName: 'Reyes',
    fullName: 'Reyes, Daniel',
    username: 'reyes.d',
    email: 'daniel.reyes@eztruckrepair.com',
    role: 'Employee',
    department: 'Mechanical Floor',
    shift: 'Main Shift 1',
    status: 'archived',
    isPunchedIn: false,
    weeklyHours: 0,
    overtimeHours: 0,
    hireDate: '2020-05-01',
    phone: '(555) 100-0023',
  },
  {
    id: 'emp-024',
    firstName: 'Victor',
    lastName: 'Sanchez',
    fullName: 'Sanchez, Victor',
    username: 'sanchez.v',
    email: 'victor.sanchez@eztruckrepair.com',
    role: 'Employee',
    department: 'Mechanical Floor',
    shift: 'Main Shift 1',
    status: 'archived',
    isPunchedIn: false,
    weeklyHours: 0,
    overtimeHours: 0,
    hireDate: '2019-11-20',
    phone: '(555) 100-0024',
  },
  {
    id: 'emp-025',
    firstName: 'Hector',
    lastName: 'Ramirez',
    fullName: 'Ramirez, Hector',
    username: 'ramirez.h',
    email: 'hector.ramirez@eztruckrepair.com',
    role: 'Employee',
    department: 'Office',
    shift: 'Main Shift 1',
    status: 'archived',
    isPunchedIn: false,
    weeklyHours: 0,
    overtimeHours: 0,
    hireDate: '2020-08-15',
    phone: '(555) 100-0025',
  },
];

export async function apiGetEmployees(
  filters?: Partial<EmployeeFilters>,
  page = 1,
  pageSize = 10
): Promise<PaginatedResponse<Employee>> {
  await new Promise((resolve) => setTimeout(resolve, 500));

  let filtered = [...MOCK_EMPLOYEES];

  if (filters?.search) {
    const q = filters.search.toLowerCase();
    filtered = filtered.filter(
      (e) =>
        e.fullName.toLowerCase().includes(q) ||
        e.email.toLowerCase().includes(q) ||
        e.department.toLowerCase().includes(q)
    );
  }

  if (filters?.status && filters.status !== 'all') {
    filtered = filtered.filter((e) => e.status === filters.status);
  }

  if (filters?.department && filters.department !== 'all') {
    filtered = filtered.filter((e) => e.department === filters.department);
  }

  if (filters?.shift && filters.shift !== 'all') {
    filtered = filtered.filter((e) => e.shift === filters.shift);
  }

  if (filters?.role && filters.role !== 'all') {
    filtered = filtered.filter((e) => e.role === filters.role);
  }

  const total = filtered.length;
  const totalPages = Math.ceil(total / pageSize);
  const start = (page - 1) * pageSize;
  const data = filtered.slice(start, start + pageSize);

  return { data, total, page, pageSize, totalPages };
}

export async function apiGetEmployee(id: string): Promise<Employee> {
  await new Promise((resolve) => setTimeout(resolve, 300));
  const emp = MOCK_EMPLOYEES.find((e) => e.id === id);
  if (!emp) throw new Error(`Employee ${id} not found`);
  return emp;
}
